export { Navbar } from "./Navbar/Navbar";
export { SplitScreen } from "./Split/SplitScreen";
export { Splitestudiantes } from "./SplitE/Splitestudiantes";
export { Curso } from "./Curso/Curso";
export { ToastRegistro } from "./Toast/Toast Registro/ToastRegistro";
export { CardEstudiante } from "./CardEstudiante/CardEstudiante";
export { CardTutor } from "./CardTutor/CardTutor";
export { PTutorHome } from "./PerfilTutorHome/PTutorHome";
export { PageLoader } from "./PageLoader/PageLoader";
export {CardWorker} from "./CardWorker/CardWorker";